### ISSUE TITLE
关于upsample层的问题

### ISSUE THREAD

**Issue by CangHaiQingYue** [205418367/TransOnnxToCaffe#2]
您好，我的upsample层中，没有‘height_scale’属性，请问这是因为pytorch版本的问题，还是onnx版本的问题。
在pytorch中的函数是F.interpolate()

**Comment by sakura-iv** [comment]
@CangHaiQingYue 你好，你这个问题解决了吗，我目前也是这个问题。。

**Comment by CangHaiQingYue** [comment]
直接把里面的factor写死。
